// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"projectName/internal/handler"
	"projectName/internal/repository"
	"projectName/internal/server"
	"projectName/internal/service"
	"projectName/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewDb(viperViper)
	client := repository.NewRedisDb(viperViper)
	repositoryRepository := repository.NewRepository(logger, db, client)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, repositoryRepository, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)

	feedRepository := repository.NewFeedRepository(repositoryRepository)
	feedService := service.NewFeedService(serviceService, repositoryRepository, feedRepository)
	feedHandler := handler.NewFeedHandler(handlerHandler, feedService)


	engine := server.NewServerHTTP(logger,repositoryRepository, userHandler,feedHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRedisDb, repository.NewRepository, repository.NewUserRepository, repository.NewFeedRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewFeedService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewFeedHandler)
